package FrontEnd;


/**
* FrontEnd/FrontEndInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/VarunPattiah/workspaceHelios/DFRSFrontEnd/src/FrontEnd.idl
* Monday, November 21, 2016 10:05:48 o'clock AM EST
*/

public interface FrontEndInterfaceOperations 
{
  String executeOperation (String method, String managerId, String firstName, String lastName, String phoneNumber, String destination, String address, String dateofBooking, String classType, String recordType, String recordId, String fieldName, String passengerID, String currentCity, String otherCity, String newValue, String remoteServerName);
} // interface FrontEndInterfaceOperations
