package idl.interfaces;


/**
* idl/interfaces/PassengerVO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/hp/workspace/DFRS_Assignment2/src/DFRSInterface.idl
* Saturday, November 5, 2016 5:05:13 o'clock PM EDT
*/

public final class PassengerVO implements org.omg.CORBA.portable.IDLEntity
{
  public String recordID = null;
  public String firstName = null;
  public String lastName = null;
  public String address = null;
  public String phoneNumber = null;
  public String destination = null;
  public String classOfFlight = null;
  public String dateOfFilight = null;
  public String message = null;
  public boolean isFlightBooked = false;

  public PassengerVO ()
  {
  } // ctor

  public PassengerVO (String _recordID, String _firstName, String _lastName, String _address, String _phoneNumber, String _destination, String _classOfFlight, String _dateOfFilight, String _message, boolean _isFlightBooked)
  {
    recordID = _recordID;
    firstName = _firstName;
    lastName = _lastName;
    address = _address;
    phoneNumber = _phoneNumber;
    destination = _destination;
    classOfFlight = _classOfFlight;
    dateOfFilight = _dateOfFilight;
    message = _message;
    isFlightBooked = _isFlightBooked;
  } // ctor

} // class PassengerVO
