package idl.interfaces;

/**
* idl/interfaces/PassengerVOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/hp/workspace/DFRS_Assignment2/src/DFRSInterface.idl
* Saturday, November 5, 2016 5:05:13 o'clock PM EDT
*/

public final class PassengerVOHolder implements org.omg.CORBA.portable.Streamable
{
  public idl.interfaces.PassengerVO value = null;

  public PassengerVOHolder ()
  {
  }

  public PassengerVOHolder (idl.interfaces.PassengerVO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = idl.interfaces.PassengerVOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    idl.interfaces.PassengerVOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return idl.interfaces.PassengerVOHelper.type ();
  }

}
