package idl.interfaces;


/**
* idl/interfaces/_DFRSInterfaceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/hp/workspace/DFRS_Assignment2/src/DFRSInterface.idl
* Saturday, November 5, 2016 5:05:13 o'clock PM EDT
*/

public class _DFRSInterfaceStub extends org.omg.CORBA.portable.ObjectImpl implements idl.interfaces.DFRSInterface
{

  public idl.interfaces.PassengerVO bookFlight (String firstName, String lastName, String address, String phoneNumber, String destination, String date, String classType)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("bookFlight", true);
                $out.write_string (firstName);
                $out.write_string (lastName);
                $out.write_string (address);
                $out.write_string (phoneNumber);
                $out.write_string (destination);
                $out.write_string (date);
                $out.write_string (classType);
                $in = _invoke ($out);
                idl.interfaces.PassengerVO $result = idl.interfaces.PassengerVOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return bookFlight (firstName, lastName, address, phoneNumber, destination, date, classType        );
            } finally {
                _releaseReply ($in);
            }
  } // bookFlight

  public int[] getBookedFlightCount (String recordType)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getBookedFlightCount", true);
                $out.write_string (recordType);
                $in = _invoke ($out);
                int $result[] = idl.interfaces.RecordCountListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getBookedFlightCount (recordType        );
            } finally {
                _releaseReply ($in);
            }
  } // getBookedFlightCount

  public idl.interfaces.FlightVO editFlightRecord (String recordID, String fieldName, String newValue)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("editFlightRecord", true);
                $out.write_string (recordID);
                $out.write_string (fieldName);
                $out.write_string (newValue);
                $in = _invoke ($out);
                idl.interfaces.FlightVO $result = idl.interfaces.FlightVOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return editFlightRecord (recordID, fieldName, newValue        );
            } finally {
                _releaseReply ($in);
            }
  } // editFlightRecord

  public boolean managerAuthentication (String userName)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("managerAuthentication", true);
                $out.write_string (userName);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return managerAuthentication (userName        );
            } finally {
                _releaseReply ($in);
            }
  } // managerAuthentication

  public idl.interfaces.PassengerVO transferReservation (String passengerID, String currentCity, String otherCity)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("transferReservation", true);
                $out.write_string (passengerID);
                $out.write_string (currentCity);
                $out.write_string (otherCity);
                $in = _invoke ($out);
                idl.interfaces.PassengerVO $result = idl.interfaces.PassengerVOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return transferReservation (passengerID, currentCity, otherCity        );
            } finally {
                _releaseReply ($in);
            }
  } // transferReservation

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:idl/interfaces/DFRSInterface:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _DFRSInterfaceStub
