package idl.interfaces;


/**
* idl/interfaces/FlightVO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/hp/workspace/DFRS_Assignment2/src/DFRSInterface.idl
* Saturday, November 5, 2016 5:05:13 o'clock PM EDT
*/

public final class FlightVO implements org.omg.CORBA.portable.IDLEntity
{
  public int flightID = (int)0;
  public String Departure = null;
  public String Destination = null;
  public String flightDate = null;
  public int economySeats = (int)0;
  public int businessSeats = (int)0;
  public int firstClassSeats = (int)0;
  public String editedBy = null;
  public boolean isAvailable = false;
  public String message = null;
  public boolean isFlightModified = false;

  public FlightVO ()
  {
  } // ctor

  public FlightVO (int _flightID, String _Departure, String _Destination, String _flightDate, int _economySeats, int _businessSeats, int _firstClassSeats, String _editedBy, boolean _isAvailable, String _message, boolean _isFlightModified)
  {
    flightID = _flightID;
    Departure = _Departure;
    Destination = _Destination;
    flightDate = _flightDate;
    economySeats = _economySeats;
    businessSeats = _businessSeats;
    firstClassSeats = _firstClassSeats;
    editedBy = _editedBy;
    isAvailable = _isAvailable;
    message = _message;
    isFlightModified = _isFlightModified;
  } // ctor

} // class FlightVO
