package idl.interfaces;


/**
* idl/interfaces/DFRSInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/VarunPattiah/workspaceHelios/DFRS_Assignment2/src/DFRSInterface.idl
* Saturday, November 5, 2016 5:05:13 o'clock PM EDT
*/

public abstract class DFRSInterfacePOA extends org.omg.PortableServer.Servant
 implements idl.interfaces.DFRSInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("bookFlight", new java.lang.Integer (0));
    _methods.put ("getBookedFlightCount", new java.lang.Integer (1));
    _methods.put ("editFlightRecord", new java.lang.Integer (2));
    _methods.put ("managerAuthentication", new java.lang.Integer (3));
    _methods.put ("transferReservation", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // idl/interfaces/DFRSInterface/bookFlight
       {
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String address = in.read_string ();
         String phoneNumber = in.read_string ();
         String destination = in.read_string ();
         String date = in.read_string ();
         String classType = in.read_string ();
         idl.interfaces.PassengerVO $result = null;
         $result = this.bookFlight (firstName, lastName, address, phoneNumber, destination, date, classType);
         out = $rh.createReply();
         idl.interfaces.PassengerVOHelper.write (out, $result);
         break;
       }

       case 1:  // idl/interfaces/DFRSInterface/getBookedFlightCount
       {
         String recordType = in.read_string ();
         int $result[] = null;
         $result = this.getBookedFlightCount (recordType);
         out = $rh.createReply();
         idl.interfaces.RecordCountListHelper.write (out, $result);
         break;
       }

       case 2:  // idl/interfaces/DFRSInterface/editFlightRecord
       {
         String recordID = in.read_string ();
         String fieldName = in.read_string ();
         String newValue = in.read_string ();
         idl.interfaces.FlightVO $result = null;
         $result = this.editFlightRecord (recordID, fieldName, newValue);
         out = $rh.createReply();
         idl.interfaces.FlightVOHelper.write (out, $result);
         break;
       }

       case 3:  // idl/interfaces/DFRSInterface/managerAuthentication
       {
         String userName = in.read_string ();
         boolean $result = false;
         $result = this.managerAuthentication (userName);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // idl/interfaces/DFRSInterface/transferReservation
       {
         String passengerID = in.read_string ();
         String currentCity = in.read_string ();
         String otherCity = in.read_string ();
         idl.interfaces.PassengerVO $result = null;
         $result = this.transferReservation (passengerID, currentCity, otherCity);
         out = $rh.createReply();
         idl.interfaces.PassengerVOHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:idl/interfaces/DFRSInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DFRSInterface _this() 
  {
    return DFRSInterfaceHelper.narrow(
    super._this_object());
  }

  public DFRSInterface _this(org.omg.CORBA.ORB orb) 
  {
    return DFRSInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class DFRSInterfacePOA
