package idl.interfaces;


/**
* idl/interfaces/DFRSInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/VarunPattiah/workspaceHelios/DFRS_Assignment2/src/DFRSInterface.idl
* Saturday, November 5, 2016 5:05:13 o'clock PM EDT
*/

public interface DFRSInterfaceOperations 
{
  idl.interfaces.PassengerVO bookFlight (String firstName, String lastName, String address, String phoneNumber, String destination, String date, String classType);
  int[] getBookedFlightCount (String recordType);
  idl.interfaces.FlightVO editFlightRecord (String recordID, String fieldName, String newValue);
  boolean managerAuthentication (String userName);
  idl.interfaces.PassengerVO transferReservation (String passengerID, String currentCity, String otherCity);
} // interface DFRSInterfaceOperations
