package idl.interfaces;


/**
* idl/interfaces/DFRSInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/VarunPattiah/workspaceHelios/DFRS_Assignment2/src/DFRSInterface.idl
* Saturday, November 5, 2016 5:05:13 o'clock PM EDT
*/

public interface DFRSInterface extends DFRSInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DFRSInterface
