package idl.interfaces;

/**
* idl/interfaces/FlightVOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/VarunPattiah/workspaceHelios/DFRS_Assignment2/src/DFRSInterface.idl
* Saturday, November 5, 2016 5:05:13 o'clock PM EDT
*/

public final class FlightVOHolder implements org.omg.CORBA.portable.Streamable
{
  public idl.interfaces.FlightVO value = null;

  public FlightVOHolder ()
  {
  }

  public FlightVOHolder (idl.interfaces.FlightVO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = idl.interfaces.FlightVOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    idl.interfaces.FlightVOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return idl.interfaces.FlightVOHelper.type ();
  }

}
