package idl.interfaces;


/**
* idl/interfaces/RecordCountListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/VarunPattiah/workspaceHelios/DFRS_Assignment2/src/DFRSInterface.idl
* Saturday, November 5, 2016 5:05:13 o'clock PM EDT
*/

public final class RecordCountListHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public RecordCountListHolder ()
  {
  }

  public RecordCountListHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = idl.interfaces.RecordCountListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    idl.interfaces.RecordCountListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return idl.interfaces.RecordCountListHelper.type ();
  }

}
